name: Update GitHub Stats

on:
  schedule:
    - cron: "0 4 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # =============================
      # DARK MODE STATS
      # =============================
      - name: Generate Dark Stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: "username=pratham1659&show_icons=true&theme=tokyonight&hide_border=true&bg_color=0D1117&title_color=FFFFFF&text_color=8B949E&icon_color=A78BFA"
          path: profile/github-stats-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # =============================
      # LIGHT MODE STATS
      # =============================
      - name: Generate Light Stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: "username=pratham1659&show_icons=true&theme=default&hide_border=true&bg_color=FFFFFF&title_color=24292F&text_color=57606A&icon_color=6A11CB"
          path: profile/github-stats-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # =============================
      # COMMIT SVG FILES
      # =============================
      - name: Commit Stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/github-stats-dark.svg
          git add profile/github-stats-light.svg

          git commit -m "Update GitHub stats" || exit 0

          git push
