name: Update GitHub Stats

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Dark Stats
        run: |
          mkdir -p profile

          curl -L \
            -A "Mozilla/5.0" \
            -w "\nHTTP_STATUS=%{http_code}\n" \
            "https://github-readme-stats.vercel.app/api?username=pratham1659&show_icons=true&theme=tokyonight&hide_border=true&bg_color=0D1117&title_color=FFFFFF&text_color=8B949E&icon_color=A78BFA" \
            -o profile/github-stats-dark.svg

          echo "Dark SVG size:"
          wc -c profile/github-stats-dark.svg

          echo "First 200 characters:"
          head -c 200 profile/github-stats-dark.svg

      - name: Download Light Stats
        run: |
          curl -L \
            -A "Mozilla/5.0" \
            -w "\nHTTP_STATUS=%{http_code}\n" \
            "https://github-readme-stats.vercel.app/api?username=pratham1659&show_icons=true&theme=default&hide_border=true&bg_color=FFFFFF&title_color=24292F&text_color=57606A&icon_color=6A11CB" \
            -o profile/github-stats-light.svg

          echo "Light SVG size:"
          wc -c profile/github-stats-light.svg

          echo "First 200 characters:"
          head -c 200 profile/github-stats-light.svg
